#!/bin/bash

for sub in `cat subjects`;do
  cd $sub;ls > list
  while read file;do
    newfile=`echo ${file,,}` # convert upper case letters to lower ones
    mv $file $newfile
  done < list
  rm list
  cd ..
  echo $sub done
done
